POST http://localhost:3001/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="README.md"

< ./README.md
--WebAppBoundary--

###
